---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  vars:
    balancing_method:
    pool_name:

  tasks:

  - name: CREATE POOL
    bigip_pool:
      provider:
        server: "{{private_ip}}"
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server_port: 8443
        validate_certs: false
      name: "{{pool_name}}"
      lb_method: "{{balancing_method}}"
      monitors: "/Common/http"
      monitor_type: "and_list"
