---

- name: Create a VIP, pool, pool members, and nodes
  hosts: big-ip01.internal
  connection: local
  tasks:
   - name: Create a pool
     bigip_pool:
         lb_method: ratio-member
         name: web
         password: admin
         server: big-ip01.internal
         slow_ramp_time: 120
         user: admin
         validate_certs: no
     delegate_to: localhost
   
   - name: Create node1
     bigip_node:
        host: 10.10.10.10
        name: node-1
        password: admin
        server: big-ip01.internal
        user: admin
        validate_certs: no
      delegate_to: localhost

  - name: Create node2
    bigip_node:
        host: 10.10.10.20
      name: node-2
      password: admin
      server: big-ip01.internal
      user: admin
      validate_certs: no
  delegate_to: localhost
