---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: cisco
  connection: network_cli
  gather_facts: no
  vars:
    temp_dir: /var/lib/awx/projects/_15__demolab/2-1-backup/backup

  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output

    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        dest: "{{ temp_dir }}/{{inventory_hostname}}.config"

    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "{{ temp_dir }}/{{inventory_hostname}}.config"
        line: "Building configuration..."
        state: absent


    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "{{ temp_dir }}/{{inventory_hostname}}.config"
        regexp: 'Current configuration.*'
        state: absent



- name: BACKUP ROUTER CONFIGURATIONS
  hosts: ansible
  gather_facts: no
  vars:
    dir: /home/ec2-user/backup
    temp_dir: /var/lib/awx/projects/_15__demolab/2-1-backup/backup/


  tasks:

    - name: CREATE DIRECTORY TO SAVE THE BACKUPS
      file:
        path: "{{dir}}" 
        state: directory
        mode: 0755


    - name: MOVE BACKUP CONFIGS TO CREATED DIRECTORY
      copy:
        src: "{{temp_dir}}"
        dest: "{{ dir }}"


