- name: FORMAT BACKUP ROUTER CONFIGURATIONS
  hosts: localhost
  gather_facts: no
  vars:
    dir: /home/student1/backup

  tasks:

    - name: Create directory for the backups
      file:
        path: "{{dir}}"
        state: directory
        mode: 0755

    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        dest: "{{ dir }}/{{inventory_hostname}}.config"

    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "{{ dir }}/{{inventory_hostname}}.config"
        line: "Building configuration..."
        state: absent

    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "{{ dir }}/{{inventory_hostname}}.config"
        regexp: 'Current configuration.*'
        state: absent

